### ISSUE TITLE
Intellij Idea freezes

### ISSUE THREAD

**Issue by urajbhandari** [bloxbean/algodea#23]
When transferring XYZ ASA from Bob to Alice (near 45:07 in the getting started video), my Intellij freezes and I need to kill the Intellij process on my Mackbook.

Intellij version 2021.1.1
Using Sandbox private network (./sandbox up)

**Comment by satran004** [comment]
Are you able to reproduce this behavior always ? I have seen this in the Transfer screen few times but was not able to reproduce it.

If you are able to reproduce it consistently, can you please provide the exact step ? (Like after selecting account from account chooser button ..)

Are you trying it on MacBook Intel or M1 ? Also, are you using it in a dual-monitor setup ?

The actual reason is that there is an invisible modal dialog which prevents the IDE to close. Somehow this issue is getting triggered for the Transfer screen. The exact steps will help to debug the problem.

**Comment by urajbhandari** [comment]
Strange, I tried after a day and it works as expected. The sandbox env was running from yesterday. I am not able to reproduce the error now. I will let you know if I can reproduce the error in the future.

My Macbook has the Intel chip and I use dual monitors.

Let me close this ticket for now. I will create a new one if necessary.
