### ISSUE TITLE
Fetching Asset from read only account

### ISSUE THREAD

**Issue by cusma** [bloxbean/algodea#7]
Fetching Asset form read only accounts in Transfer builder fails. I wasn’t able to copy the error log because it automatically clears on Transfer builder tab closing.

**Comment by satran004** [comment]
Hi @cusma, 
Just tried with a read-only account as "From Account". Yes it fails. 

Reason - In "Transfer Builder" UI,  it currently needs "From Mnemonic" to derive "From Address". And as "From Mnemonic" is empty for read-only account, it fails.  As of now, the primary use-case for this UI is to transfer algo/asa and mnemonic is required for signing.

**But I am assuming you are trying to just export the txn to json here.**
If that's the case, I think we don't need Mnemonic for "**Export Tx**". so we can just rely on the "From Address" field instead of always trying to derive address from mnemonic for assets discovery.

I will fix this in the next release.

But if you are trying to just see the assets of an account , you can do so from the "Account Details" UI. Just right-click on the account row and select "Show Details".

**Comment by cusma** [comment]
Hi @satran004, that's correct: I was trying to ExportTx to be able to use it for the construction of a Group Transaction.

Thanks for the confirmation!

**Comment by satran004** [comment]
Similar issues #8 and #9 fixed for Stateful contract and Asset txn.

@cusma , A new release v0.3.3 is now available with this fix. You may want to try it. This version is not yet available in the IntelliJ market place. So you need to download and install manually from here https://github.com/bloxbean/algodea/releases/tag/v0.3.3

**Comment by cusma** [comment]
Great, I'll do it an keep you posted in case of feedbacks.
